### ISSUE TITLE
Address warnings from CI build (update github actions) 

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-granite#106]
See https://github.com/redhat-developer/vscode-granite/actions/runs/11464923631

<img width="1340" alt="Screenshot 2024-10-23 at 14 47 58" src="https://github.com/user-attachments/assets/3cba844d-31f1-436c-8cf9-4e9adad8fa19">

**Comment by lavanyaj3** [comment]
<img width="1704" alt="image" src="https://github.com/user-attachments/assets/40d31c63-ba34-43c6-bac4-cf965109b52c">

removed the warnings in build by adding new test areas for ubuntu and mac
Also xvfb is included directly in the Linux test step without sudo
