### ISSUE TITLE
Windows silent install

### ISSUE THREAD

**Issue by jamescho72** [redhat-developer/vscode-granite#116]
Script Windows silent installer for ollama
OllamaSetup.exe /Silent

For common experience across Mac, Linux, Windows

**Comment by fbricon** [comment]
<img width="844" alt="Capture d’écran 2024-10-29 154155" src="https://github.com/user-attachments/assets/81ab4d80-c630-456d-a1d1-c9a5f7cb7181">

<img width="843" alt="Capture d’écran 2024-10-29 154102" src="https://github.com/user-attachments/assets/90683d80-f0d4-4d64-8406-6a3d4aa29e8a">
