### ISSUE TITLE
Add meaningful content in the readme

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-granite#50]
- explain what this extension does
- links to some granite code doc
- add some gif
- how to test CI builds
- link to contributing guide

**Comment by fbricon** [comment]
@athirakm94 can you update the readme to add a link to the contributing guide?

**Comment by athirakm94** [comment]
Sure @fbricon

**Comment by athirakm94** [comment]
Hi @fbricon 
created PR #94 
please let me know any additional details need to be added in the same.

**Comment by fbricon** [comment]
Was fixed with #94
