### ISSUE TITLE
Add meaningful description in wizard page

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-granite#72]
Add meaningful description in wizard page, between the title and the ollama status

**Comment by athirakm94** [comment]
Hi @fbricon 
i have  added  the description ,please let me know your suggestion on the  below screenshot attached 
<img width="954" alt="Screenshot 2024-10-09 at 9 52 38 AM" src="https://github.com/user-attachments/assets/afbbc534-93eb-49ea-a877-95f199066827">

**Comment by fbricon** [comment]
- remove the word "description"
- please summarize the description even further, get rid of bullet points. 
- remove border, use the darker background, ask @SachinS10-lab for help if needed

**Comment by athirakm94** [comment]
hi @fbricon 
i have made the changes mentioned please find the uodated screen shot for the UI and let me know your suggestions on the
same
<img width="935" alt="Screenshot 2024-10-10 at 5 12 28 PM" src="https://github.com/user-attachments/assets/9e1beea3-8605-4889-8da7-21de6b8a074d">
<img width="911" alt="Screenshot 2024-10-10 at 5 12 42 PM" src="https://github.com/user-attachments/assets/f945a104-79ec-40be-8752-bd469a346877">
<img width="923" alt="Screenshot 2024-10-10 at 5 13 01 PM" src="https://github.com/user-attachments/assets/bc7279d3-f016-4223-bae4-3c3bdf6dc553">
<img width="941" alt="Screenshot 2024-10-10 at 5 13 13 PM" src="https://github.com/user-attachments/assets/1e46edcb-3419-4da7-afe0-53ffcc9d32d8">

**Comment by fbricon** [comment]
The summary is misleading IMO. The extension itself is not an AI assistant, but merely a configurator to help streamline the installation of Granite Code models into ollama, and their configuration in Continue. 

As for the UI, I would give the block the same width as the one below it. Text feels too cramped, maybe increase the line height.

@jamescho72 thoughts?

**Comment by athirakm94** [comment]
Hi @fbricon  @jamescho72 
i have added the changes please find the  screen short below and let me know your suggestions

<img width="852" alt="Screenshot 2024-10-14 at 1 22 21 PM" src="https://github.com/user-attachments/assets/1b9b4299-5614-4670-8f2a-6c5b3bb9fe91">

**Comment by fbricon** [comment]
Fixed with #87 

<img width="1840" alt="Screenshot 2024-10-15 at 15 02 53" src="https://github.com/user-attachments/assets/e0765be9-1277-40fa-be6a-50635e222506">
