### ISSUE TITLE
"Setup IBM Granite Code" screen didn't show instructions about how to install Ollama in VS Code Editor on Dev Sandbox

### ISSUE THREAD

**Issue by dmytro-ndp** [redhat-developer/vscode-granite#73]
`Granite Code AI-Assistant extension` v0.0.1 displayed "Setup IBM Granite Code" screen without instructions about how to install Ollama in VS Code Editor on Dev Sandbox:
![Screenshot from 2024-10-08 17-51-58](https://github.com/user-attachments/assets/bbd2d184-1e68-4f67-b112-05bd9e9bcf27)

### Steps to reproduce
1. Download https://github.com/redhat-developer/vscode-granite/releases/download/latest/vscode-granite-0.0.1.vsix
2. Go to Dev Sandbox, open Dev Space.
3. Go to "_User Dashboard > Create workspace_" page and start Empty workspace
4. Wait on VS Code Editor to open, and install `Granite Code AI-Assistant` extension from the local vscode-granite-0.0.1.vsix file.
5. Wait on `Granite Code AI-Assistant` extension  to be installed and "_Setup IBM Granite Code_" page is opened.

### Expected result
"_Setup IBM Granite Code_" page shows [instructions how to install Ollama server](https://github.com/redhat-developer/vscode-granite/blob/main/src/ollama/ollamaServer.ts#L24-L37).

### Actual result
"Setup IBM Granite Code" page didn't show instructions about how to install Ollama server.
There was an error shown in the _Extension Host (Remote) Output_:
```
`2024-10-08 13:03:44.129 [error] Error: Command "which brew" failed with exit code "1".
	at ChildProcess.<anonymous> (/checode/remote/extensions/redhat.vscode-granite-0.0.1/dist/extension.js:21:38610)
	at ChildProcess.emit (node:events:519:28)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:339:12)
```

**Comment by fbricon** [comment]
@dmytro-ndp can you try the latest build from https://github.com/redhat-developer/vscode-granite/releases/tag/latest?

**Comment by dmytro-ndp** [comment]
@fbricon : I tried latest build with Java Lombok sample on Devevloper Sandbox, and it worked:
![Screenshot from 2024-10-14 17-36-01](https://github.com/user-attachments/assets/959d6551-1147-425e-bab7-ca64f247df98)

Few notes:
1) it was not clear how to reopen "Setup IBM Granite Code as your code assistant with Continue" page

2) "_Install from script_" scenario required sudo rights which were not achievable in the Developer Sandbox workspace out of the box, if I understood it correctly (@ibuziuk cc).

**Comment by fbricon** [comment]
> I tried latest build of extension with Java Lombok sample on Devevloper Sandbox, and it worked: ![Screenshot from 2024-1
> 1. it was not clear how to reopen "Setup IBM Granite Code as your code assistant with Continue" page

we'll add some instructions on the wizard about the "Granite: Setup Granite Code as code assistant" command, available from the command palette

> 2. "_Install from script_" scenario required sudo rights which were not achievable in the Developer Sandbox workspace when using default UBI image, if I understood it correctly (@ibuziuk cc).

this is [ollama's own install script](https://github.com/ollama/ollama/blob/main/scripts/install.sh). Could you maybe provide one that is specific to Dev Sandbox?

**Comment by dmytro-ndp** [comment]
@fbricon : thank you for heads up!
About:
>>"Install from script" scenario required sudo rights which were not achievable in the Developer Sandbox workspace when using default UBI image, if I understood it correctly (@ibuziuk cc).

> this is [ollama's own install script](https://github.com/ollama/ollama/blob/main/scripts/install.sh). Could you maybe provide one that is specific to Dev Sandbox?

There is no script, but devfile.yaml developed by @ibuziuk : https://github.com/redhat-developer-demos/cde-ollama-continue/blob/main/devfile.yaml

Documentation : https://developers.redhat.com/articles/2024/08/12/integrate-private-ai-coding-assistant-ollama?source=sso#start_the_cloud_development_environment
