### ISSUE TITLE
Add the options to not change existing models

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-granite#9]
If a user wants to pick only one of the tab completion or chat models, and keep using an existing one (eg. chat:granite, completion:deepseek-coder), it should be doable. Currently both models are overridden 100% of the time.

**Comment by SachinS10-lab** [comment]
Hi @fbricon ,
I've a doubt. Is it possible to get current selected chat model from the continue? I tried, but couldn't found a way to do that. 
But I got all downloaded chat models and showed inside the combo box and also added a checkbox for resetting the default value. I'm currently working on reset functionality.

<img width="912" alt="image" src="https://github.com/user-attachments/assets/2611e9da-e93f-4a42-a6e1-b80e26a0705c">

**Comment by fbricon** [comment]
> Is it possible to get current selected chat model from the continue?

No you can't at the moment

I would like to keep it as simple as possible:
- simply add : "Keep existing configuration" options to all 3 combos.
- no new section with checkbox

That's it. And I'm not sold on displaying "Downloaded" instead of the size.

**Comment by harshmittalibm** [comment]
What if we do "Ollama list" cmd to get the list of already installed models and ignore those that are already installed?

**Comment by fbricon** [comment]
I don't understand. You still need to be able to select any model we propose

**Comment by fbricon** [comment]
Closed with #77
