### ISSUE TITLE
Display instructions on how to re-open the wizard

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-granite#91]
At the bottom of the wizard, display instructions how to reopen the wizard by using the command palette and the "Granite: Setup Granite Code as code assistant" command, in a smaller font

**Comment by lavanyaj3** [comment]
You mean we have to give instructions in the bottom of the welcome page or does it need to appear like a popup maked in the screenshot. Could you please confirm
<img width="716" alt="image" src="https://github.com/user-attachments/assets/962767f6-34b9-4f98-b387-2e14a34b25a0">

**Comment by fbricon** [comment]
At the bottom, just like I described

**Comment by lavanyaj3** [comment]
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/d5785d3d-14a1-4900-aa26-cc58ee9a4416">


@fbricon, could you please confirm if the display instructions for reopening the wizard are ready to go?

**Comment by fbricon** [comment]
no it should not be a popup. Just some text below the main box

**Comment by lavanyaj3** [comment]
<img width="1487" alt="image" src="https://github.com/user-attachments/assets/00a7907c-ba0a-4e1e-8bdf-84bb478bb50f">

Its now appearing like this as an alert message at the bottom right corner.  

Now i changed it to test below the main box. Please confirm the change is good to proceed

<img width="1487" alt="image" src="https://github.com/user-attachments/assets/987d4045-0ed6-4b58-96a8-d6c98e773dae">

**Comment by fbricon** [comment]
Please use the same width as the rest, otherwise it looks really weird. I think it'll look better if using the same dark background as the description block at the top

**Comment by lavanyaj3** [comment]
<img width="1191" alt="image" src="https://github.com/user-attachments/assets/0850922c-b25a-48d3-bc53-f7646e705cf1">
made the modification . please let me know for any suggestions

**Comment by fbricon** [comment]
Move "Granite: Setup ... assistant" to the next line and we'll be good to go

**Comment by fbricon** [comment]
"To reopen this wizard ..."

**Comment by fbricon** [comment]
Looks good now

**Comment by lavanyaj3** [comment]
Raised PR: #119
