### ISSUE TITLE
Improvements for Red Hat OpenShift Dev Spaces

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/vscode-granite#96]
Currently, there are a few concerns mainly related to 'ollama' availability in the CDE:

1. If a user installs an extension in the CDE where ollama is not available, they will be asked to install it with sudo permissions:

<img width="891" alt="Screenshot 2024-10-17 at 11 52 53" src="https://github.com/user-attachments/assets/0b00d5fe-9d8d-4e3c-be5d-76819eaf8811">

In general, containers running as root is a significant security risk + containers are supposed to be immutable and installing anything inside the container is not recommended since after the restart all the packages will vanish. What is more containers are running using the Arbitrary User IDs (This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node).

In terms of Dev Spaces if ollama is expected to be used it should be defined as part of devfile as described in https://developers.redhat.com/articles/2024/08/12/integrate-private-ai-coding-assistant-ollama

2. if a user installs the extension in the CDE where ollama is installed e.g. 'Ollama' getting started sample on Developer Sandbox:

the extension detects ollama, and seem to configure the granite model, but in reality another model is used:

<img width="1570" alt="Screenshot 2024-10-17 at 12 08 36" src="https://github.com/user-attachments/assets/702ea8ca-6de8-4767-bba1-d64e2af5d91c">

Steps to reproduce:
- Go to https://workspaces.openshift.com/
- Create a workspace based on the 'Ollama' getting started sapmple
- Once workspace is started install the extention
- SUCEESS: extension detecs that Ollama is running
- Download and Configure Granite model via wizzard
- SUCCESS: Continue dropdown is updated with the 'granite' model
- Ask 'Who Are You' in the chat
- ERROR: OpenAI model is used 
```
I am an AI language model developed by OpenAI. I can answer your questions, summarize long pieces of text, and generate human-like text based on my training data. I am designed to assist with a wide range of tasks, from writing emails to tutoring in math.
```

**Comment by fbricon** [comment]
Fixed with #97.

The "I'm an Open AI model" is simply Granite hallucinating, nothing we can do here. We're waiting for updated models
